FROM node:20-slim
RUN corepack enable && corepack prepare pnpm@latest --activate
WORKDIR /app
COPY packages/web/package.json .
RUN pnpm install
COPY packages/web .
EXPOSE 4321
CMD ["pnpm", "dev", "--host", "0.0.0.0"]
