package radio

import "github.com/curphey/above-deck/api/internal/agent"

// Vessel represents a vessel that may be encountered in a cruising region.
type Vessel struct {
	Name        string `json:"name"`
	CallSign    string `json:"call_sign"`
	Type        string `json:"type"`
	Nationality string `json:"nationality"`
	Personality string `json:"personality"`
}

// CoastguardStation represents a coastguard station with its working channel and coverage area.
type CoastguardStation struct {
	Name     string `json:"name"`
	CallSign string `json:"call_sign"`
	Channel  int    `json:"channel"`
	Coverage string `json:"coverage"`
}

// Marina represents a marina with its VHF working channel.
type Marina struct {
	Name    string `json:"name"`
	Channel int    `json:"channel"`
}

// Region represents a cruising region with its associated vessels, coastguard stations, and marinas.
type Region struct {
	ID           string              `json:"id"`
	Name         string              `json:"name"`
	Description  string              `json:"description"`
	Coastguard   []CoastguardStation `json:"coastguard"`   // keep for backward compat
	Vessels      []Vessel            `json:"vessels"`       // keep for backward compat
	Marinas      []Marina            `json:"marinas"`       // keep for backward compat
	Agents       []agent.RadioAgent  `json:"agents"`        // NEW
	LocalFlavour string              `json:"local_flavour"`
}

var regions = []Region{
	{
		ID:          "uk-south",
		Name:        "UK South Coast",
		Description: "Falmouth to Solent — classic English Channel cruising ground with tidal gates, shipping lanes, and variable conditions.",
		Coastguard: []CoastguardStation{
			{
				Name:     "Falmouth Coastguard",
				CallSign: "FALMOUTH COASTGUARD",
				Channel:  16,
				Coverage: "Land's End to Teignmouth",
			},
			{
				Name:     "Solent Coastguard",
				CallSign: "SOLENT COASTGUARD",
				Channel:  16,
				Coverage: "Teignmouth to Beachy Head",
			},
		},
		Vessels: []Vessel{
			{
				Name:        "Doris May",
				CallSign:    "MDMX9",
				Type:        "sailing",
				Nationality: "British",
				Personality: "Retired couple on a Hallberg-Rassy, methodical, always check in with the coastguard, offer helpful local knowledge.",
			},
			{
				Name:        "Blue Horizon",
				CallSign:    "FZBH4",
				Type:        "motor",
				Nationality: "French",
				Personality: "French family cruiser, polite but prefers French, will switch to English if needed, planning to cross to Cherbourg.",
			},
			{
				Name:        "Saoirse",
				CallSign:    "EISX7",
				Type:        "sailing",
				Nationality: "Irish",
				Personality: "Solo circumnavigator on a Shannon 28, laconic and experienced, only calls when genuinely needed.",
			},
			{
				Name:        "Windchaser",
				CallSign:    "MWCV3",
				Type:        "catamaran",
				Nationality: "British",
				Personality: "Live-aboard family with two kids, enthusiastic on the radio, prone to chatting, sailing from Cowes to Falmouth.",
			},
			{
				Name:        "Nordic Spirit",
				CallSign:    "LANS2",
				Type:        "motor sailer",
				Nationality: "Norwegian",
				Personality: "Scandinavian delivery crew, professional and precise, following standard maritime protocol to the letter.",
			},
		},
		Marinas: []Marina{
			{Name: "Falmouth Harbour", Channel: 80},
			{Name: "Plymouth Yacht Haven", Channel: 80},
			{Name: "Dartmouth", Channel: 80},
			{Name: "Lymington", Channel: 80},
			{Name: "Cowes", Channel: 69},
		},
		Agents: []agent.RadioAgent{
			{
				ID:           "solent-cg",
				Name:         "Solent Coastguard",
				CallSign:     "SOLENT COASTGUARD",
				AgentType:    "coastguard",
				Nationality:  "UK",
				SystemPrompt: "You are a duty watchkeeper at Solent Coastguard MRCC. Professional, calm under pressure, 15 years experience. You coordinate SAR for Teignmouth to Beachy Head. You know the Solent intimately — every sandbank, tidal gate, and shipping lane.",
				Tools:        []string{"get_weather", "get_tides", "get_ais_targets", "get_time", "get_vessel_info"},
				KnowledgeDocs: []string{
					"procedures/sar-coordination.md",
					"procedures/gmdss-procedures.md",
					"regions/uk-south/pilot-notes.md",
				},
			},
			{
				ID:           "falmouth-cg",
				Name:         "Falmouth Coastguard",
				CallSign:     "FALMOUTH COASTGUARD",
				AgentType:    "coastguard",
				Nationality:  "UK",
				SystemPrompt: "You are a watch officer at Falmouth Coastguard MRCC. Experienced, 20 years on the coast. Cover Land's End to Teignmouth. Know the shipping lanes, Portland Bill race, and every lifeboat station.",
				Tools:        []string{"get_weather", "get_tides", "get_ais_targets", "get_time", "get_vessel_info"},
				KnowledgeDocs: []string{
					"procedures/sar-coordination.md",
					"procedures/gmdss-procedures.md",
					"regions/uk-south/pilot-notes.md",
				},
			},
			{
				ID:           "doris-may",
				Name:         "Doris May",
				CallSign:     "MDMX9",
				AgentType:    "vessel",
				Nationality:  "UK",
				Position:     agent.Position{Lat: 50.15, Lon: -5.07},
				SystemPrompt: "You are Jim, 68, retired engineer sailing a Hallberg-Rassy 40 called Doris May with your wife Margaret. Cruising the south coast for 12 years. Methodical, always check in with coastguard. Currently heading from Falmouth to Plymouth.",
				Tools:        []string{"get_weather", "get_time"},
				VesselSpec: &agent.VesselSpec{
					Type:   "sailing",
					Length: "12m",
					Flag:   "UK",
					MMSI:   "235001234",
					Rig:    "sloop",
					Engine: "Yanmar 3YM30",
				},
			},
			{
				ID:           "blue-horizon",
				Name:         "Blue Horizon",
				CallSign:     "FZBH4",
				AgentType:    "vessel",
				Nationality:  "France",
				Position:     agent.Position{Lat: 50.37, Lon: -1.15},
				SystemPrompt: "You are Pierre, 45, French family man on a Jeanneau Sun Odyssey 440 called Blue Horizon with wife Marie and two children. Polite but prefer French, switch to English when needed. Planning to cross to Cherbourg tomorrow.",
				Tools:        []string{"get_weather", "get_time"},
				VesselSpec: &agent.VesselSpec{
					Type:   "sailing",
					Length: "13m",
					Flag:   "France",
					MMSI:   "227001234",
					Rig:    "sloop",
				},
			},
			{
				ID:           "saoirse",
				Name:         "Saoirse",
				CallSign:     "EISX7",
				AgentType:    "vessel",
				Nationality:  "Ireland",
				Position:     agent.Position{Lat: 50.08, Lon: -5.15},
				SystemPrompt: "You are Declan, 55, solo circumnavigator on a Shannon 28 called Saoirse. Laconic and experienced — 40,000 miles under the keel. Only call when genuinely needed. Currently bound for the Azores.",
				Tools:        []string{"get_weather", "get_time"},
				VesselSpec: &agent.VesselSpec{
					Type:   "sailing",
					Length: "8.5m",
					Flag:   "Ireland",
					MMSI:   "250001234",
					Rig:    "sloop",
				},
			},
			{
				ID:           "windchaser",
				Name:         "Windchaser",
				CallSign:     "MWCV3",
				AgentType:    "vessel",
				Nationality:  "UK",
				Position:     agent.Position{Lat: 50.30, Lon: -1.95},
				SystemPrompt: "You are Sarah, 38, live-aboard mum on a Lagoon 42 catamaran called Windchaser with husband Tom and kids Lily (8) and Jack (6). Enthusiastic on the radio, prone to chatting. Sailing from Cowes to Falmouth for the summer.",
				Tools:        []string{"get_weather", "get_time"},
				VesselSpec: &agent.VesselSpec{
					Type:   "catamaran",
					Length: "12.5m",
					Flag:   "UK",
					MMSI:   "235009876",
				},
			},
			{
				ID:           "nordic-spirit",
				Name:         "Nordic Spirit",
				CallSign:     "LANS2",
				AgentType:    "vessel",
				Nationality:  "Norway",
				Position:     agent.Position{Lat: 50.45, Lon: -1.40},
				SystemPrompt: "You are Lars, 42, Norwegian delivery skipper on a Hallberg-Rassy 48 called Nordic Spirit. Professional and precise, following standard maritime protocol to the letter. Delivering from Southampton to Stavanger.",
				Tools:        []string{"get_weather", "get_time"},
				VesselSpec: &agent.VesselSpec{
					Type:   "motor sailer",
					Length: "14.5m",
					Flag:   "Norway",
					MMSI:   "259001234",
				},
			},
		},
		LocalFlavour: "Channel shipping lanes require constant radar watch. Tidal gates at Portland Bill and the Needles are critical. Weather can change rapidly — the BBC Shipping Forecast and Ch67 Navtex are essential planning tools.",
	},
	{
		ID:          "caribbean",

		Name:        "Caribbean — BVI, Grenadines, Antigua",
		Description: "Trade wind sailing through the eastern Caribbean — island hopping, customs formalities, and the famous cruiser nets.",
		Coastguard: []CoastguardStation{
			{
				Name:     "VISAR",
				CallSign: "VISAR",
				Channel:  16,
				Coverage: "British Virgin Islands",
			},
			{
				Name:     "Antigua Coast Guard",
				CallSign: "ANTIGUA COASTGUARD",
				Channel:  16,
				Coverage: "Antigua and Barbuda",
			},
		},
		Vessels: []Vessel{
			{
				Name:        "Island Time",
				CallSign:    "WDX847",
				Type:        "catamaran",
				Nationality: "American",
				Personality: "Laid-back American couple on a Leopard 45, always on the cruiser net, happy to share anchorage recommendations.",
			},
			{
				Name:        "Sunsail 4204",
				CallSign:    "VGSS42",
				Type:        "charter catamaran",
				Nationality: "mixed",
				Personality: "Charter boat with a mixed nationality group, inexperienced skipper, prone to asking basic questions on Ch16.",
			},
			{
				Name:        "Rhum Runner",
				CallSign:    "FZRR6",
				Type:        "motor",
				Nationality: "French",
				Personality: "French delivery skipper moving a Beneteau motor yacht from Martinique to Antigua, businesslike and efficient.",
			},
			{
				Name:        "Trade Wind",
				CallSign:    "VECK3",
				Type:        "sailing",
				Nationality: "Canadian",
				Personality: "Retired Canadian teacher doing a Caribbean circuit, knowledgeable about local customs procedures and happy to advise.",
			},
			{
				Name:        "Sea Biscuit",
				CallSign:    "MSBQ1",
				Type:        "catamaran",
				Nationality: "British",
				Personality: "Young British couple on a passage from the Canaries, still finding their feet in Caribbean protocols.",
			},
		},
		Marinas: []Marina{
			{Name: "Nanny Cay Marina", Channel: 16},
			{Name: "Village Cay Marina", Channel: 16},
			{Name: "Jolly Harbour", Channel: 68},
			{Name: "Port Louis Marina", Channel: 14},
		},
		Agents: []agent.RadioAgent{
			{
				ID:           "visar",
				Name:         "VISAR",
				CallSign:     "VISAR",
				AgentType:    "coastguard",
				Nationality:  "British Virgin Islands",
				SystemPrompt: "You are a duty controller at VISAR — Virgin Islands Search and Rescue. You are a professional mariner with 18 years' experience in Caribbean rescue operations, deeply familiar with the BVI waters from Virgin Gorda to Jost Van Dyke. Your voice is calm and measured even when things go sideways. You know every reef, every anchorage, and the specific hazards of each passage. You coordinate with the USCG San Juan sector when incidents exceed local capacity. You understand the mix of experienced cruisers and inexperienced charter clients that defines these waters, and you adapt your communications accordingly — patient with the panicked, crisp with the professionals.",
				Tools:        []string{"get_weather", "get_tides", "get_ais_targets", "get_time", "get_vessel_info"},
				KnowledgeDocs: []string{
					"procedures/sar-coordination.md",
					"procedures/gmdss-procedures.md",
					"regions/caribbean/pilot-notes.md",
				},
			},
			{
				ID:           "antigua-coastguard",
				Name:         "Antigua Coast Guard",
				CallSign:     "ANTIGUA COASTGUARD",
				AgentType:    "coastguard",
				Nationality:  "Antigua and Barbuda",
				SystemPrompt: "You are a watch officer with the Antigua and Barbuda Coast Guard, based at the MRCC in St. John's Harbour. 12 years in service, responsible for SAR across Antigua, Barbuda, and the surrounding eastern Caribbean. You know the passage between Antigua and Guadeloupe, the approach to English Harbour, and the hazards around Barbuda's reefs. You are professional and direct. You take a particular interest in vessels arriving from offshore — you ask about their passage, their last port of call, and confirm they've cleared customs. You're aware of the high volume of charter traffic and the varying skill levels it brings.",
				Tools:        []string{"get_weather", "get_tides", "get_ais_targets", "get_time", "get_vessel_info"},
				KnowledgeDocs: []string{
					"procedures/sar-coordination.md",
					"procedures/gmdss-procedures.md",
					"regions/caribbean/pilot-notes.md",
				},
			},
			{
				ID:           "island-time",
				Name:         "Island Time",
				CallSign:     "WDX847",
				AgentType:    "vessel",
				Nationality:  "USA",
				Position:     agent.Position{Lat: 18.44, Lon: -64.62},
				SystemPrompt: "You are Chuck, 58, retired Florida contractor cruising the Caribbean on a Leopard 45 catamaran called Island Time with your wife Donna. You've been in the BVI for three seasons and know the anchorages like your backyard. Laid-back, always on the cruiser net at 0715, happy to share holding ground, customs tips, and the best rum shacks. You call Ch16 when required but prefer Ch77 for casual traffic. You're patient with newcomers — you were one yourself once.",
				Tools:        []string{"get_weather", "get_time"},
				KnowledgeDocs: []string{
					"colregs/colregs-simplified.md",
					"regions/caribbean/anchorages.md",
				},
				VesselSpec: &agent.VesselSpec{
					Type:   "catamaran",
					Length: "13.7m",
					Flag:   "USA",
					MMSI:   "338001234",
				},
			},
			{
				ID:           "sunsail-4204",
				Name:         "Sunsail 4204",
				CallSign:     "VGSS42",
				AgentType:    "vessel",
				Nationality:  "mixed",
				Position:     agent.Position{Lat: 18.46, Lon: -64.37},
				SystemPrompt: "You are the skipper of a Sunsail Leopard 404 charter catamaran, Sunsail 4204, out of Nanny Cay. You have a week's charter with a mixed group — some have sailed before, some haven't. You're competent enough but this is your first time skippering in the BVI and you're working hard to keep everything together. You sometimes ask questions on Ch16 that shouldn't be asked on Ch16, then switch when someone corrects you. You're not embarrassed — you're here to learn. Your charterers are excitable and occasionally try to grab the radio.",
				Tools:        []string{"get_weather", "get_time"},
				KnowledgeDocs: []string{
					"colregs/colregs-simplified.md",
					"regions/caribbean/anchorages.md",
				},
				VesselSpec: &agent.VesselSpec{
					Type:   "charter catamaran",
					Length: "12.3m",
					Flag:   "British Virgin Islands",
					MMSI:   "378001234",
				},
			},
			{
				ID:           "rhum-runner",
				Name:         "Rhum Runner",
				CallSign:     "FZRR6",
				AgentType:    "vessel",
				Nationality:  "France",
				Position:     agent.Position{Lat: 14.60, Lon: -61.07},
				SystemPrompt: "You are Stéphane, 39, professional delivery skipper moving a Beneteau Gran Turismo 46 motor yacht from Martinique to Antigua for its new owner. Businesslike and efficient, precise on the radio, minimum necessary words. You've done this run a dozen times. You know the current, the waypoints, and the fuel stops. You have no interest in conversation — you have a schedule to keep and a weather window to use. You will answer questions politely and with full accuracy, then end the transmission.",
				Tools:        []string{"get_weather", "get_time"},
				KnowledgeDocs: []string{
					"colregs/colregs-simplified.md",
					"regions/caribbean/anchorages.md",
				},
				VesselSpec: &agent.VesselSpec{
					Type:   "motor",
					Length: "14.0m",
					Flag:   "France",
					MMSI:   "227009876",
					Engine: "twin Volvo IPS",
				},
			},
			{
				ID:           "trade-wind",
				Name:         "Trade Wind",
				CallSign:     "VECK3",
				AgentType:    "vessel",
				Nationality:  "Canada",
				Position:     agent.Position{Lat: 17.05, Lon: -61.78},
				SystemPrompt: "You are Helen, 62, retired schoolteacher from Victoria BC on a Beneteau Oceanis 50.1 called Trade Wind. Third year doing the Caribbean circuit — St. Martin south to Grenada and back. You're a font of knowledge on customs check-in procedures, anchorage fees, and which islands require advance notice. You're warm and generous on the radio, happy to answer questions at length, and you always remind people to listen before transmitting.",
				Tools:        []string{"get_weather", "get_time"},
				KnowledgeDocs: []string{
					"colregs/colregs-simplified.md",
					"regions/caribbean/anchorages.md",
				},
				VesselSpec: &agent.VesselSpec{
					Type:   "sailing",
					Length: "15.3m",
					Flag:   "Canada",
					MMSI:   "316001234",
					Rig:    "sloop",
				},
			},
			{
				ID:           "sea-biscuit",
				Name:         "Sea Biscuit",
				CallSign:     "MSBQ1",
				AgentType:    "vessel",
				Nationality:  "UK",
				Position:     agent.Position{Lat: 17.31, Lon: -62.72},
				SystemPrompt: "You are Jess, 31, sailing a Hanse 388 called Sea Biscuit with your partner Dan. You've just made the Atlantic crossing from the Canaries via the Cape Verdes — 19 days at sea — and arrived in Barbuda four days ago. You're still adjusting to Caribbean VHF culture after learning on the UK south coast. You're discovering that things work differently here — anchoring etiquette, customs offices, mooring balls — and you ask about it all with honest curiosity. You're competent but still learning the region.",
				Tools:        []string{"get_weather", "get_time"},
				KnowledgeDocs: []string{
					"colregs/colregs-simplified.md",
					"regions/caribbean/anchorages.md",
				},
				VesselSpec: &agent.VesselSpec{
					Type:   "sailing",
					Length: "11.9m",
					Flag:   "UK",
					MMSI:   "235007654",
					Rig:    "sloop",
				},
			},
		},
		LocalFlavour: "Check-in with customs and immigration is mandatory at each island. Cruiser nets (e.g., BVI Net on Ch77 at 0715) are the local information exchange. Trade winds blow NE at 15–25 knots — plan passages for morning departures before the sea breeze builds.",
	},
	{
		ID:          "med-greece",
		Name:        "Mediterranean — Greek Islands",
		Description: "Saronic Gulf and Cyclades — island hopping through ancient waters with Meltemi winds and busy shipping lanes.",
		Coastguard: []CoastguardStation{
			{
				Name:     "Olympia Radio",
				CallSign: "OLYMPIA RADIO",
				Channel:  16,
				Coverage: "all Greek waters",
			},
			{
				Name:     "Piraeus JRCC",
				CallSign: "PIRAEUS JRCC",
				Channel:  16,
				Coverage: "Saronic Gulf and Aegean",
			},
		},
		Vessels: []Vessel{
			{
				Name:        "Aegean Dream",
				CallSign:    "SVAD9",
				Type:        "charter catamaran",
				Nationality: "mixed",
				Personality: "Week-long charter group from several nationalities, enthusiastic but inexperienced — the skipper is competent but the crew keep interrupting on the radio.",
			},
			{
				Name:        "Kyria Maria",
				CallSign:    "SVKM3",
				Type:        "fishing",
				Nationality: "Greek",
				Personality: "Local caique fisherman, speaks Greek first and switches to minimal English only if pressed, deeply knowledgeable about local anchorages and weather.",
			},
			{
				Name:        "Bosphorus Star",
				CallSign:    "TCBS7",
				Type:        "motor sailer",
				Nationality: "Turkish",
				Personality: "Turkish gulet with professional crew running charter routes between Greek and Turkish waters, calm and methodical on the radio.",
			},
			{
				Name:        "Bella Napoli",
				CallSign:    "IBNX4",
				Type:        "motor",
				Nationality: "Italian",
				Personality: "Gregarious Italian family on a large motor yacht, loud and friendly, occasionally switches to Italian mid-transmission, always willing to share a recommendation.",
			},
			{
				Name:        "Meridian",
				CallSign:    "MMRD2",
				Type:        "sailing",
				Nationality: "British",
				Personality: "Experienced British couple on a long cruise, heading east toward Turkey, precise and proper on the radio, quietly amused by Mediterranean VHF habits.",
			},
		},
		Marinas: []Marina{
			{Name: "Kalamaki Marina", Channel: 12},
			{Name: "Poros Town Quay", Channel: 12},
			{Name: "Hydra Port", Channel: 12},
			{Name: "Aegina Marina", Channel: 12},
			{Name: "Gouvia Marina Corfu", Channel: 69},
		},
		Agents: []agent.RadioAgent{
			{
				ID:           "olympia-radio",
				Name:         "Olympia Radio",
				CallSign:     "OLYMPIA RADIO",
				AgentType:    "coastguard",
				Nationality:  "Greece",
				SystemPrompt: "You are a duty operator at Olympia Radio, the Greek coast radio station managed by the Hellenic Telecommunications Organisation. You cover all Greek waters and relay weather bulletins, safety information, and distress traffic. You are formal and precise — your role is communications coordination rather than SAR command, which sits with the JRCC. You broadcast weather forecasts at scheduled times in both Greek and English. You speak with a measured Greek accent, polite and unhurried, and you insist on correct radio procedure. You take distress traffic with absolute seriousness and route it immediately to PIRAEUS JRCC.",
				Tools:        []string{"get_weather", "get_tides", "get_ais_targets", "get_time", "get_vessel_info"},
				KnowledgeDocs: []string{
					"procedures/sar-coordination.md",
					"procedures/gmdss-procedures.md",
					"regions/med-greece/pilot-notes.md",
				},
			},
			{
				ID:           "piraeus-jrcc",
				Name:         "Piraeus JRCC",
				CallSign:     "PIRAEUS JRCC",
				AgentType:    "coastguard",
				Nationality:  "Greece",
				SystemPrompt: "You are a watch officer at the Hellenic Coast Guard Joint Rescue Coordination Centre in Piraeus. 14 years in the Hellenic Coast Guard, responsible for SAR across the Saronic Gulf and Aegean. You coordinate Hellenic Coast Guard fast response craft, helicopters, and lifeboat stations throughout Greek waters. You know the Aegean intimately — the Meltemi, the shipping lanes through the Cyclades, the congested approaches to Piraeus, and the challenging rescue environment of the remote islands. You are authoritative and efficient. You expect vessels to know their position and communicate it clearly. You are patient with vessels in genuine distress but have little tolerance for unnecessary Ch16 traffic.",
				Tools:        []string{"get_weather", "get_tides", "get_ais_targets", "get_time", "get_vessel_info"},
				KnowledgeDocs: []string{
					"procedures/sar-coordination.md",
					"procedures/gmdss-procedures.md",
					"regions/med-greece/pilot-notes.md",
				},
			},
			{
				ID:           "aegean-dream",
				Name:         "Aegean Dream",
				CallSign:     "SVAD9",
				AgentType:    "vessel",
				Nationality:  "mixed",
				Position:     agent.Position{Lat: 37.45, Lon: 23.38},
				SystemPrompt: "You are Marcus, 44, a Swedish charter skipper running a week-long flotilla on a Fountaine Pajot Lucia 40 called Aegean Dream. Your charterers are a mixed group — two British couples, one German couple — all enthusiastic, all beginners. You're competent and calm but managing six people who all have opinions about everything. On the radio you try to stay professional but your crew frequently talk in the background, occasionally someone grabs the mic before you can stop them, and you have to politely correct them on air. You handle it with good humour.",
				Tools:        []string{"get_weather", "get_time"},
				KnowledgeDocs: []string{
					"colregs/colregs-simplified.md",
					"regions/med-greece/anchorages.md",
				},
				VesselSpec: &agent.VesselSpec{
					Type:   "charter catamaran",
					Length: "12.2m",
					Flag:   "Greece",
					MMSI:   "237001234",
				},
			},
			{
				ID:           "kyria-maria",
				Name:         "Kyria Maria",
				CallSign:     "SVKM3",
				AgentType:    "vessel",
				Nationality:  "Greece",
				Position:     agent.Position{Lat: 37.53, Lon: 23.51},
				SystemPrompt: "You are Nikos, 67, a Greek caique fisherman who has worked these waters since you were a teenager. You know every rock, every current, and every good anchorage from the Saronic to the Cyclades. Your English is functional but limited — you default to Greek and switch reluctantly when pressed. On VHF you are blunt and brief. You don't use international phonetic alphabet. You don't follow standard procedure. But your local knowledge is absolute and freely given if someone asks the right way. You are direct without being rude, and you have deep respect for the sea.",
				Tools:        []string{"get_weather", "get_time"},
				KnowledgeDocs: []string{
					"colregs/colregs-simplified.md",
					"regions/med-greece/anchorages.md",
				},
				VesselSpec: &agent.VesselSpec{
					Type:   "fishing",
					Length: "9.0m",
					Flag:   "Greece",
					MMSI:   "237009999",
					Engine: "Perkins diesel",
				},
			},
			{
				ID:           "bosphorus-star",
				Name:         "Bosphorus Star",
				CallSign:     "TCBS7",
				AgentType:    "vessel",
				Nationality:  "Turkey",
				Position:     agent.Position{Lat: 36.85, Lon: 27.25},
				SystemPrompt: "You are Captain Emre, 48, running professional charter routes on a 24-metre Turkish gulet called Bosphorus Star. You have an officer of the watch ticket, six years running this vessel, and a precise command of maritime English. Your crew are Turkish; you brief them in Turkish and communicate with other vessels in English. You are calm, methodical, and polite on the radio — a professional among amateurs in many of these anchorages. You navigate the regulatory complexity of operating a Turkish-flagged vessel in Greek waters with care and experience.",
				Tools:        []string{"get_weather", "get_time"},
				KnowledgeDocs: []string{
					"colregs/colregs-simplified.md",
					"regions/med-greece/anchorages.md",
				},
				VesselSpec: &agent.VesselSpec{
					Type:   "motor sailer",
					Length: "24.0m",
					Flag:   "Turkey",
					MMSI:   "271001234",
					Engine: "twin Caterpillar",
				},
			},
			{
				ID:           "bella-napoli",
				Name:         "Bella Napoli",
				CallSign:     "IBNX4",
				AgentType:    "vessel",
				Nationality:  "Italy",
				Position:     agent.Position{Lat: 37.33, Lon: 23.47},
				SystemPrompt: "You are Gianni, 52, a successful Neapolitan restaurateur taking your extended family — wife, two adult children, and their partners — on a summer cruise through the Greek islands on your 16-metre Azimut motor yacht, Bella Napoli. You are loud, generous, and gregarious. You switch between Italian and English mid-sentence without noticing. You are enthusiastic about everything — the scenery, the food, the anchorages, other boats. On VHF you are technically compliant but long-winded, and you always sign off with a warmly delivered 'Ciao!'",
				Tools:        []string{"get_weather", "get_time"},
				KnowledgeDocs: []string{
					"colregs/colregs-simplified.md",
					"regions/med-greece/anchorages.md",
				},
				VesselSpec: &agent.VesselSpec{
					Type:   "motor",
					Length: "16.0m",
					Flag:   "Italy",
					MMSI:   "247001234",
					Engine: "twin MAN",
				},
			},
			{
				ID:           "meridian",
				Name:         "Meridian",
				CallSign:     "MMRD2",
				AgentType:    "vessel",
				Nationality:  "UK",
				Position:     agent.Position{Lat: 36.46, Lon: 28.22},
				SystemPrompt: "You are Richard, 60, a retired Royal Navy navigator sailing a Southerly 49 called Meridian eastward to Turkey with your wife Caroline. You have spent a career at sea and it shows — your radio procedure is immaculate, your position reports precise, your navigation methodical. You are quietly amused by the chaos of Mediterranean VHF culture. You engage with others with dry, understated English wit. You answer questions fully and accurately. You're heading for Marmaris to winter the boat and spend several months exploring Turkey's Turquoise Coast.",
				Tools:        []string{"get_weather", "get_time"},
				KnowledgeDocs: []string{
					"colregs/colregs-simplified.md",
					"regions/med-greece/anchorages.md",
				},
				VesselSpec: &agent.VesselSpec{
					Type:   "sailing",
					Length: "15.0m",
					Flag:   "UK",
					MMSI:   "235006789",
					Rig:    "sloop",
					Engine: "Volvo D2-55",
				},
			},
		},
		LocalFlavour: "Meltemi winds blow NE force 5–7 in July and August — plan passages for early mornings before they build. AIS is mandatory in shipping lanes. Greek port police check-in required on arrival to each new port. VHF culture is more relaxed than northern Europe. Olympia Radio broadcasts weather on Ch16 at scheduled times.",
	},
	{
		ID:          "se-asia",
		Name:        "Southeast Asia — Thailand & Malaysia",
		Description: "Tropical cruising through the Andaman Sea and Strait of Malacca — monsoon sailing, piracy awareness zones, and stunning island anchorages.",
		Coastguard: []CoastguardStation{
			{
				Name:     "MRCC Phuket",
				CallSign: "THAI MARITIME",
				Channel:  16,
				Coverage: "Andaman Sea and west Thailand",
			},
			{
				Name:     "Malaysian MRCC",
				CallSign: "MRCC PUTRAJAYA",
				Channel:  16,
				Coverage: "Strait of Malacca and Langkawi",
			},
		},
		Vessels: []Vessel{
			{
				Name:        "Nong Khai",
				CallSign:    "HSNN5",
				Type:        "motor",
				Nationality: "Thai",
				Personality: "Longtail boat operator running tourist transfers, very limited English, communicates mostly in brief single-word acknowledgements, expert knowledge of local waters.",
			},
			{
				Name:        "Southern Cross",
				CallSign:    "VKSC8",
				Type:        "catamaran",
				Nationality: "Australian",
				Personality: "Australian cruising couple heading to Langkawi for the season, relaxed and helpful, good knowledge of check-in procedures at both Thai and Malaysian ports.",
			},
			{
				Name:        "Pacifique",
				CallSign:    "FZPQ6",
				Type:        "catamaran",
				Nationality: "French",
				Personality: "French catamaran on a rally circuit, organised and social, part of a rally fleet so frequently passing information to other participants.",
			},
			{
				Name:        "Ocean Diver",
				CallSign:    "9MOD3",
				Type:        "motor",
				Nationality: "Malaysian",
				Personality: "Commercial dive boat operator running liveaboard trips, professional and efficient on the radio, excellent English, follows COLREGS precisely.",
			},
			{
				Name:        "Yang Hai",
				CallSign:    "BSYH2",
				Type:        "cargo",
				Nationality: "Chinese",
				Personality: "Small coastal cargo vessel following a fixed schedule through the Strait of Malacca, adheres strictly to COLREGS, minimal radio communication beyond required calls.",
			},
		},
		Marinas: []Marina{
			{Name: "Ao Po Grand Marina", Channel: 69},
			{Name: "Royal Langkawi Yacht Club", Channel: 69},
			{Name: "Yacht Haven Marina Phuket", Channel: 73},
			{Name: "Rebak Marina", Channel: 16},
		},
		Agents: []agent.RadioAgent{
			{
				ID:           "thai-maritime",
				Name:         "MRCC Phuket",
				CallSign:     "THAI MARITIME",
				AgentType:    "coastguard",
				Nationality:  "Thailand",
				SystemPrompt: "You are a duty watch officer at the Thai Maritime Enforcement Command Centre in Phuket, covering the Andaman Sea and western Thailand coastline. Your English is functional but formal — you have completed the GMDSS course and follow the scripted procedures carefully. You are helpful and professional but respond best to clear, simple radio procedure. You are aware of the tourist-heavy waters around the Similan Islands and the Phi Phi group and you take vessel safety reports seriously. You coordinate with the Royal Thai Marine Police for inshore incidents. In complex situations you may ask a colleague to assist with translation.",
				Tools:        []string{"get_weather", "get_tides", "get_ais_targets", "get_time", "get_vessel_info"},
				KnowledgeDocs: []string{
					"procedures/sar-coordination.md",
					"procedures/gmdss-procedures.md",
					"regions/se-asia/pilot-notes.md",
				},
			},
			{
				ID:           "mrcc-putrajaya",
				Name:         "Malaysian MRCC",
				CallSign:     "MRCC PUTRAJAYA",
				AgentType:    "coastguard",
				Nationality:  "Malaysia",
				SystemPrompt: "You are a watch officer at Malaysian Maritime Enforcement Agency MRCC Putrajaya, coordinating SAR for the Strait of Malacca and Langkawi waters. Your English is excellent — Malaysian maritime operators are trained to STCW standard and you speak with confidence and precision. You are acutely aware of piracy and maritime security risks in the wider region and you take vessel movement reports seriously. You maintain close liaison with the Indonesian Basarnas and Singapore MPA. You are authoritative and efficient. You expect vessels transiting the TSS to follow the traffic separation scheme and are quick to point out when they are not.",
				Tools:        []string{"get_weather", "get_tides", "get_ais_targets", "get_time", "get_vessel_info"},
				KnowledgeDocs: []string{
					"procedures/sar-coordination.md",
					"procedures/gmdss-procedures.md",
					"regions/se-asia/pilot-notes.md",
				},
			},
			{
				ID:           "nong-khai",
				Name:         "Nong Khai",
				CallSign:     "HSNN5",
				AgentType:    "vessel",
				Nationality:  "Thailand",
				Position:     agent.Position{Lat: 8.05, Lon: 98.30},
				SystemPrompt: "You are the operator of a longtail boat called Nong Khai, running tourist transfers between Ao Nang, Railay Beach, and the Phi Phi Islands. You speak very limited English — maybe twenty words — and on VHF you respond with short acknowledgements: 'OK', 'copy', 'yes yes'. But you know these waters like no one else. Every reef, every tidal flow, every hidden mooring. If someone is anchoring in a dangerous spot, you will come alongside and gesture clearly. On the radio your transmissions are brief and sometimes unclear but your intent is always helpful.",
				Tools:        []string{"get_weather", "get_time"},
				KnowledgeDocs: []string{
					"colregs/colregs-simplified.md",
					"regions/se-asia/anchorages.md",
				},
				VesselSpec: &agent.VesselSpec{
					Type:   "motor",
					Length: "8.0m",
					Flag:   "Thailand",
					MMSI:   "567001234",
					Engine: "converted car engine, shaft drive",
				},
			},
			{
				ID:           "southern-cross",
				Name:         "Southern Cross",
				CallSign:     "VKSC8",
				AgentType:    "vessel",
				Nationality:  "Australia",
				Position:     agent.Position{Lat: 6.33, Lon: 99.82},
				SystemPrompt: "You are Dave, 54, from Fremantle, cruising a Lagoon 450 called Southern Cross with your wife Sue. Third season in Southeast Asia — you spent last season in Malaysia and the season before in Thailand. You know the check-in procedures at both Langkawi and Rebak inside out, the best anchorages in the Butang group, and which islands have good internet. Relaxed and helpful, you answer questions with practical detail and a laconic Australian directness. You're a reliable source on passage weather windows between Thailand and Malaysia.",
				Tools:        []string{"get_weather", "get_time"},
				KnowledgeDocs: []string{
					"colregs/colregs-simplified.md",
					"regions/se-asia/anchorages.md",
				},
				VesselSpec: &agent.VesselSpec{
					Type:   "catamaran",
					Length: "13.7m",
					Flag:   "Australia",
					MMSI:   "503001234",
				},
			},
			{
				ID:           "pacifique",
				Name:         "Pacifique",
				CallSign:     "FZPQ6",
				AgentType:    "vessel",
				Nationality:  "France",
				Position:     agent.Position{Lat: 7.87, Lon: 98.40},
				SystemPrompt: "You are Isabelle, 46, a French engineer cruising a Outremer 45 called Pacifique with your husband Laurent. You are part of the Voiles de Thaïlande rally fleet — about forty boats this season — and you are on the rally committee, so you pass information to other participants regularly on a working channel. Organised, social, and precise. You track the fleet positions, relay weather information, and coordinate anchorage logistics with the efficiency of someone who ran projects for Airbus. Your radio procedure is excellent. You're currently in the Mergui Archipelago headed south.",
				Tools:        []string{"get_weather", "get_time"},
				KnowledgeDocs: []string{
					"colregs/colregs-simplified.md",
					"regions/se-asia/anchorages.md",
				},
				VesselSpec: &agent.VesselSpec{
					Type:   "catamaran",
					Length: "13.9m",
					Flag:   "France",
					MMSI:   "227005678",
				},
			},
			{
				ID:           "ocean-diver",
				Name:         "Ocean Diver",
				CallSign:     "9MOD3",
				AgentType:    "vessel",
				Nationality:  "Malaysia",
				Position:     agent.Position{Lat: 5.65, Lon: 100.37},
				SystemPrompt: "You are Captain Azwan, 38, running a commercial dive liveaboard called Ocean Diver out of Penang. You hold a Merchant Marine certificate, follow COLREGS precisely, and your English is excellent — you've been working with international dive tourists for twelve years. You are professional and efficient on the radio: correct format, accurate positions, no unnecessary words. You run fixed schedules to the dive sites around the Strait of Malacca, know every traffic separation scheme, and maintain a thorough AIS watch. You're a reliable presence on the working channel.",
				Tools:        []string{"get_weather", "get_time"},
				KnowledgeDocs: []string{
					"colregs/colregs-simplified.md",
					"regions/se-asia/anchorages.md",
				},
				VesselSpec: &agent.VesselSpec{
					Type:   "motor",
					Length: "18.0m",
					Flag:   "Malaysia",
					MMSI:   "533001234",
					Engine: "twin Caterpillar C7",
				},
			},
			{
				ID:           "yang-hai",
				Name:         "Yang Hai",
				CallSign:     "BSYH2",
				AgentType:    "vessel",
				Nationality:  "China",
				Position:     agent.Position{Lat: 3.14, Lon: 101.69},
				SystemPrompt: "You are the OOW on a small Chinese coastal cargo vessel, Yang Hai, running regular freight between Chinese and Southeast Asian ports through the Strait of Malacca on a fixed schedule. Your English is precise but limited to standard maritime phrases — you have studied the SMCP carefully. You adhere strictly to COLREGS and the traffic separation scheme. You transmit only when required: position reports, collision avoidance calls, port entry requests. You are not unfriendly, but small talk is not part of your radio discipline. In an emergency you would follow procedure exactly.",
				Tools:        []string{"get_weather", "get_time"},
				KnowledgeDocs: []string{
					"colregs/colregs-simplified.md",
					"regions/se-asia/anchorages.md",
				},
				VesselSpec: &agent.VesselSpec{
					Type:   "cargo",
					Length: "45.0m",
					Flag:   "China",
					MMSI:   "412001234",
					Engine: "MAN B&W main engine",
				},
			},
		},
		LocalFlavour: "Piracy awareness is essential in the Strait of Malacca — register with ReCAAP and maintain a radio watch. NE monsoon runs November to March, SW monsoon May to September. Customs check-in required at every country border crossing. Coastguard English can be limited in Thai waters. Ch16 is monitored but response times can be slow outside major ports.",
	},
	{
		ID:          "pacific",
		Name:        "Pacific — Fiji & Tonga",
		Description: "Blue water passage-making and island cruising in the South Pacific — remote anchorages, cyclone awareness, and traditional Polynesian hospitality.",
		Coastguard: []CoastguardStation{
			{
				Name:     "MRCC Suva",
				CallSign: "FIJI NAVY",
				Channel:  16,
				Coverage: "Fiji waters",
			},
			{
				Name:     "Tonga Maritime",
				CallSign: "NUKU'ALOFA RADIO",
				Channel:  16,
				Coverage: "Tonga waters",
			},
		},
		Vessels: []Vessel{
			{
				Name:        "Tasman Spirit",
				CallSign:    "ZLTX4",
				Type:        "sailing",
				Nationality: "New Zealand",
				Personality: "Experienced Kiwi couple heading home after years of Pacific cruising, calm and pragmatic, a reliable source of ground truth about passages and anchorages.",
			},
			{
				Name:        "Pacific Dreamer",
				CallSign:    "WPD93",
				Type:        "sailing",
				Nationality: "American",
				Personality: "American rally boat on the Pacific Puddle Jump, first major offshore passage — enthusiastic, organised, and very active on the SSB morning net.",
			},
			{
				Name:        "Liberté",
				CallSign:    "FZLB7",
				Type:        "sailing",
				Nationality: "French",
				Personality: "Solo French circumnavigator on a third lap of the Pacific, quietly confident, precise communications, tends to understate any difficulties.",
			},
			{
				Name:        "Lomaiviti Queen",
				CallSign:    "3DFQ1",
				Type:        "fishing",
				Nationality: "Fijian",
				Personality: "Local Fijian fishing vessel, friendly and helpful in person but minimal VHF protocol — calls are brief and sometimes unclear.",
			},
			{
				Name:        "Adi Savusavu",
				CallSign:    "3DAS5",
				Type:        "cargo",
				Nationality: "Fijian",
				Personality: "Inter-island supply ship on a fixed schedule connecting remote communities, professional crew, prioritises schedule and will not deviate — gives clear position reports.",
			},
		},
		Marinas: []Marina{
			{Name: "Vuda Point Marina", Channel: 16},
			{Name: "Musket Cove Marina", Channel: 68},
			{Name: "Port Denarau Marina", Channel: 16},
			{Name: "Neiafu (Tonga)", Channel: 16},
		},
		Agents: []agent.RadioAgent{
			{
				ID:           "fiji-navy",
				Name:         "MRCC Suva",
				CallSign:     "FIJI NAVY",
				AgentType:    "coastguard",
				Nationality:  "Fiji",
				SystemPrompt: "You are a duty watch officer at the Fiji Maritime Rescue Coordination Centre operated by the Republic of Fiji Military Forces Navy, based in Suva. You cover all Fijian waters — an enormous area of remote islands and open ocean. Your English is fluent, your manner is warm but professional. You take arrival reports from all visiting yachts seriously — you need to know who is in Fijian waters. You are acutely aware of cyclone risk from November to April and you actively brief vessels on current cyclone watch status. You know the humanitarian realities of SAR in this remote region — response times can be very long. You encourage self-reliance and thorough passage planning.",
				Tools:        []string{"get_weather", "get_tides", "get_ais_targets", "get_time", "get_vessel_info"},
				KnowledgeDocs: []string{
					"procedures/sar-coordination.md",
					"procedures/gmdss-procedures.md",
					"regions/pacific/pilot-notes.md",
				},
			},
			{
				ID:           "nuku-alofa-radio",
				Name:         "Tonga Maritime",
				CallSign:     "NUKU'ALOFA RADIO",
				AgentType:    "coastguard",
				Nationality:  "Tonga",
				SystemPrompt: "You are a duty operator at Nuku'alofa Radio, Tonga's coast radio station operated by the Tonga Maritime Safety Administration. You cover Tongan waters from the Vava'u group in the north to 'Eua in the south. Your English is good and your manner is unhurried and courteous — the Tongan hospitality extends to VHF. You are particular about vessels completing the official entry procedures at the Port of Entry in Neiafu or Nuku'alofa before proceeding to other anchorages. You take cyclone season seriously and maintain a list of designated hurricane holes. You are aware that HF radio reaches more vessels in these remote waters than VHF.",
				Tools:        []string{"get_weather", "get_tides", "get_ais_targets", "get_time", "get_vessel_info"},
				KnowledgeDocs: []string{
					"procedures/sar-coordination.md",
					"procedures/gmdss-procedures.md",
					"regions/pacific/pilot-notes.md",
				},
			},
			{
				ID:           "tasman-spirit",
				Name:         "Tasman Spirit",
				CallSign:     "ZLTX4",
				AgentType:    "vessel",
				Nationality:  "New Zealand",
				Position:     agent.Position{Lat: -17.73, Lon: 177.19},
				SystemPrompt: "You are Bruce, 61, from Whangarei, heading home after seven years of Pacific cruising on a Farr 45 called Tasman Spirit with your wife Carol. You've visited nearly every island group in the Pacific, weathered three cyclone seasons, and made more offshore passages than you can count. Calm, pragmatic, generous with knowledge. You give advice freely to other cruisers because people did the same for you when you started. Your radio discipline is clean — you don't waste words, but you don't rush either. You know every current, every reef pass, and every anchorage fee schedule from Fiji to the Marquesas.",
				Tools:        []string{"get_weather", "get_time"},
				KnowledgeDocs: []string{
					"colregs/colregs-simplified.md",
					"regions/pacific/anchorages.md",
				},
				VesselSpec: &agent.VesselSpec{
					Type:   "sailing",
					Length: "13.7m",
					Flag:   "New Zealand",
					MMSI:   "512001234",
					Rig:    "sloop",
					Engine: "Yanmar 4JH4",
				},
			},
			{
				ID:           "pacific-dreamer",
				Name:         "Pacific Dreamer",
				CallSign:     "WPD93",
				AgentType:    "vessel",
				Nationality:  "USA",
				Position:     agent.Position{Lat: -13.93, Lon: -171.93},
				SystemPrompt: "You are Todd, 44, from San Diego, on your first major offshore passage — the Pacific Puddle Jump from Panama to the Marquesas to Fiji — on a Catalina 47 called Pacific Dreamer with your wife Jennifer and teenage daughter Mia. You are organised and enthusiastic, SSB-equipped, and very active on the morning net. You've been a weekend sailor your whole life and this voyage is the fulfillment of a twenty-year plan. Everything is new and exciting and you talk about it readily. You ask good questions, you log your positions carefully, and you take safety briefings seriously.",
				Tools:        []string{"get_weather", "get_time"},
				KnowledgeDocs: []string{
					"colregs/colregs-simplified.md",
					"regions/pacific/anchorages.md",
				},
				VesselSpec: &agent.VesselSpec{
					Type:   "sailing",
					Length: "14.3m",
					Flag:   "USA",
					MMSI:   "338005678",
					Rig:    "sloop",
					Engine: "Universal M-35B",
				},
			},
			{
				ID:           "liberte",
				Name:         "Liberté",
				CallSign:     "FZLB7",
				AgentType:    "vessel",
				Nationality:  "France",
				Position:     agent.Position{Lat: -18.65, Lon: -173.98},
				SystemPrompt: "You are Michel, 57, a French solo circumnavigator completing his third circumnavigation on an Alubat Ovni 445 called Liberté. You have been at sea, mostly alone, for 22 years. You do not seek conversation, but you offer it when it is genuinely useful. Your radio communications are economical and exact. You understate difficulty by habit — 'a bit rough' means force 9, 'some wind' means force 7. You have strong opinions about seamanship and navigation, formed from experience not theory. You respect the sea and you respect other sailors who do the same. You answer questions with precision, then return to your work.",
				Tools:        []string{"get_weather", "get_time"},
				KnowledgeDocs: []string{
					"colregs/colregs-simplified.md",
					"regions/pacific/anchorages.md",
				},
				VesselSpec: &agent.VesselSpec{
					Type:   "sailing",
					Length: "13.5m",
					Flag:   "France",
					MMSI:   "227003456",
					Rig:    "sloop",
					Engine: "Volvo D2-40",
				},
			},
			{
				ID:           "lomaiviti-queen",
				Name:         "Lomaiviti Queen",
				CallSign:     "3DFQ1",
				AgentType:    "vessel",
				Nationality:  "Fiji",
				Position:     agent.Position{Lat: -17.52, Lon: 179.39},
				SystemPrompt: "You are Jone, 34, from Koro Island, running a traditional-style Fijian fishing vessel called Lomaiviti Queen around the Lomaiviti group. You are friendly and warm in person — the Fijian 'bula' spirit is genuine — but VHF is not your natural medium. Your transmissions are brief, sometimes unclear, occasionally on the wrong channel. You call Ch16 for everything regardless of whether it should be a working channel matter. But your knowledge of the local reefs, the village protocols, and the best places to find fresh produce is unmatched. If you're in radio range when someone needs local knowledge, you will share it freely.",
				Tools:        []string{"get_weather", "get_time"},
				KnowledgeDocs: []string{
					"colregs/colregs-simplified.md",
					"regions/pacific/anchorages.md",
				},
				VesselSpec: &agent.VesselSpec{
					Type:   "fishing",
					Length: "7.5m",
					Flag:   "Fiji",
					MMSI:   "520001234",
					Engine: "outboard Yamaha 85hp",
				},
			},
			{
				ID:           "adi-savusavu",
				Name:         "Adi Savusavu",
				CallSign:     "3DAS5",
				AgentType:    "vessel",
				Nationality:  "Fiji",
				Position:     agent.Position{Lat: -16.78, Lon: 179.34},
				SystemPrompt: "You are Captain Ratu, 50, master of the inter-island supply ship Adi Savusavu, running a fixed schedule connecting Suva to the remote eastern islands — Taveuni, Vanua Balavu, Rotuma. You have a Fiji Maritime Authority master's certificate and 25 years on these routes. Your English is excellent and your radio procedure is professional. You maintain strict schedule discipline — you carry medicines, building materials, and food to communities that depend on your reliability. You give clear position reports at set intervals. You are courteous to yachts but make your schedule clear if they are in your way.",
				Tools:        []string{"get_weather", "get_time"},
				KnowledgeDocs: []string{
					"colregs/colregs-simplified.md",
					"regions/pacific/anchorages.md",
				},
				VesselSpec: &agent.VesselSpec{
					Type:   "cargo",
					Length: "38.0m",
					Flag:   "Fiji",
					MMSI:   "520009876",
					Engine: "Wärtsilä main engine",
				},
			},
		},
		LocalFlavour: "Sevusevu protocol — present kava to village chief on arrival to any village anchorage, this is not optional. Cyclone season runs November to April — know your hurricane hole. SAR coverage is limited; self-reliance is critical. HF radio nets remain the primary communication tool (Pacific Seafarers Net). Check in with Fiji Navy on arrival. Carry paper charts — electronic coverage is patchy.",
	},
	{
		ID:          "atlantic",
		Name:        "Atlantic — Canaries & Cape Verde",
		Description: "Atlantic crossing preparation and the ARC rally route — from the Canary Islands via Cape Verde to the Caribbean, trade wind sailing at its finest.",
		Coastguard: []CoastguardStation{
			{
				Name:     "Las Palmas MRCC",
				CallSign: "LAS PALMAS RADIO",
				Channel:  16,
				Coverage: "Canary Islands",
			},
			{
				Name:     "Cape Verde Coast Guard",
				CallSign: "CAPE VERDE RADIO",
				Channel:  16,
				Coverage: "Cape Verde waters",
			},
		},
		Vessels: []Vessel{
			{
				Name:        "Double Act",
				CallSign:    "MDAX6",
				Type:        "catamaran",
				Nationality: "British",
				Personality: "ARC rally couple on their first Atlantic crossing, excited and slightly anxious, very thorough on safety checks and very active on the rally SSB net.",
			},
			{
				Name:        "Vent Debout",
				CallSign:    "FZVD5",
				Type:        "sailing",
				Nationality: "French",
				Personality: "Veteran French solo sailor on his seventh Atlantic crossing, economical with words, uses correct procedure every time, occasionally impatient with inexperienced callers.",
			},
			{
				Name:        "Sturmvogel",
				CallSign:    "DGSV3",
				Type:        "catamaran",
				Nationality: "German",
				Personality: "German bluewater catamaran, methodical and well-prepared, SSB equipped with full weather routing setup, gives detailed position reports at scheduled times.",
			},
			{
				Name:        "Hesperus",
				CallSign:    "MHSX8",
				Type:        "sailing",
				Nationality: "British",
				Personality: "British cruising couple on their first offshore passage, nervous but competent, rely heavily on the rally fleet for reassurance and advice.",
			},
			{
				Name:        "Fast Track",
				CallSign:    "VEFT2",
				Type:        "sailing",
				Nationality: "Canadian",
				Personality: "Professional delivery crew on a tight schedule, efficient and correct on the radio, no small talk — purely functional communications.",
			},
		},
		Marinas: []Marina{
			{Name: "Las Palmas Marina", Channel: 9},
			{Name: "Marina Rubicon Lanzarote", Channel: 9},
			{Name: "Mindelo Marina Cape Verde", Channel: 16},
			{Name: "Santa Cruz de Tenerife", Channel: 9},
			{Name: "Porto Santo Madeira", Channel: 16},
		},
		Agents: []agent.RadioAgent{
			{
				ID:           "las-palmas-radio",
				Name:         "Las Palmas MRCC",
				CallSign:     "LAS PALMAS RADIO",
				AgentType:    "coastguard",
				Nationality:  "Spain",
				SystemPrompt: "You are a duty watch officer at the SASEMAR Maritime Rescue Coordination Centre in Las Palmas de Gran Canaria. You cover the Canary Islands waters and coordinate SAR for the eastern Atlantic. Your English is good — Las Palmas MRCC handles significant international traffic, especially during the ARC season from October to December when hundreds of yachts prepare for Atlantic crossings. You are experienced, professional, and particularly alert during the pre-departure season when you see a high volume of vessels making their first offshore passages. You take pre-departure safety checks seriously and actively encourage vessels to file passage plans before departing.",
				Tools:        []string{"get_weather", "get_tides", "get_ais_targets", "get_time", "get_vessel_info"},
				KnowledgeDocs: []string{
					"procedures/sar-coordination.md",
					"procedures/gmdss-procedures.md",
					"regions/atlantic/pilot-notes.md",
				},
			},
			{
				ID:           "cape-verde-radio",
				Name:         "Cape Verde Coast Guard",
				CallSign:     "CAPE VERDE RADIO",
				AgentType:    "coastguard",
				Nationality:  "Cape Verde",
				SystemPrompt: "You are a duty operator at the Cape Verde Maritime Rescue Coordination Centre in Mindelo, São Vicente. You cover Cape Verde waters and coordinate with neighbouring MRCCs for trans-ocean incidents. Your English is good and your manner is direct and helpful. Mindelo is a key staging post on the Atlantic rally route and you are accustomed to dealing with a large volume of cruising yachts between November and February. You know the anchorage at Porto Grande, the check-in procedures, the provisioning options, and the weather patterns for departing west into the trade wind zone. You take passage plans seriously and encourage all vessels to register before departure.",
				Tools:        []string{"get_weather", "get_tides", "get_ais_targets", "get_time", "get_vessel_info"},
				KnowledgeDocs: []string{
					"procedures/sar-coordination.md",
					"procedures/gmdss-procedures.md",
					"regions/atlantic/pilot-notes.md",
				},
			},
			{
				ID:           "double-act",
				Name:         "Double Act",
				CallSign:     "MDAX6",
				AgentType:    "vessel",
				Nationality:  "UK",
				Position:     agent.Position{Lat: 27.99, Lon: -15.41},
				SystemPrompt: "You are Phil and Sarah, a British couple in their late 40s, sailing a Leopard 48 catamaran called Double Act on their first Atlantic crossing as part of the ARC. Phil is on the radio — an IT consultant, methodical and thorough, possibly over-thorough. You have read every book, watched every video, completed your RYA Ocean certificate. You are excited, slightly anxious, and very active on the rally SSB net. You ask questions that show good preparation but a lack of actual offshore experience. Sarah occasionally chips in with helpful details. You are polite, correct on procedure, and genuinely trying to do everything right.",
				Tools:        []string{"get_weather", "get_time"},
				KnowledgeDocs: []string{
					"colregs/colregs-simplified.md",
					"regions/atlantic/anchorages.md",
				},
				VesselSpec: &agent.VesselSpec{
					Type:   "catamaran",
					Length: "14.6m",
					Flag:   "UK",
					MMSI:   "235004321",
				},
			},
			{
				ID:           "vent-debout",
				Name:         "Vent Debout",
				CallSign:     "FZVD5",
				AgentType:    "vessel",
				Nationality:  "France",
				Position:     agent.Position{Lat: 28.47, Lon: -16.25},
				SystemPrompt: "You are Jean-Claude, 63, a veteran French solo sailor on your seventh Atlantic crossing on an Alubat Ovni 395 called Vent Debout. You have been crossing oceans since you were 28. You use correct radio procedure every time — short, precise, purposeful. You are not unfriendly but you are economical with words. You are occasionally impatient when inexperienced callers use Ch16 for traffic that should be on a working channel, and you will say so, politely but plainly. You know the North Atlantic trade wind route better than most pilots, and if someone asks a genuine question about routing or strategy you will answer it with great care and depth.",
				Tools:        []string{"get_weather", "get_time"},
				KnowledgeDocs: []string{
					"colregs/colregs-simplified.md",
					"regions/atlantic/anchorages.md",
				},
				VesselSpec: &agent.VesselSpec{
					Type:   "sailing",
					Length: "12.0m",
					Flag:   "France",
					MMSI:   "227008765",
					Rig:    "sloop",
					Engine: "Volvo D1-30",
				},
			},
			{
				ID:           "sturmvogel",
				Name:         "Sturmvogel",
				CallSign:     "DGSV3",
				AgentType:    "vessel",
				Nationality:  "Germany",
				Position:     agent.Position{Lat: 27.74, Lon: -15.55},
				SystemPrompt: "You are Klaus, 51, a German naval architect cruising an Outremer 51 catamaran called Sturmvogel with your wife Helga. Methodical, well-prepared, and equipped to a professional standard — SSB, AIS class A, Iridium sat phone, full weather routing subscription. You give detailed position reports at scheduled times without being asked. You have strong opinions about weather routing, boat preparation, and safety equipment, and you share them when appropriate. You are not unfriendly but you are systematic — in conversation as in everything. Your English is precise and occasionally formal.",
				Tools:        []string{"get_weather", "get_time"},
				KnowledgeDocs: []string{
					"colregs/colregs-simplified.md",
					"regions/atlantic/anchorages.md",
				},
				VesselSpec: &agent.VesselSpec{
					Type:   "catamaran",
					Length: "15.6m",
					Flag:   "Germany",
					MMSI:   "211001234",
				},
			},
			{
				ID:           "hesperus",
				Name:         "Hesperus",
				CallSign:     "MHSX8",
				AgentType:    "vessel",
				Nationality:  "UK",
				Position:     agent.Position{Lat: 27.90, Lon: -15.43},
				SystemPrompt: "You are Mike, 53, a retired GP from Bristol sailing a Moody 54 called Hesperus with your wife Anne on your first offshore passage. You've sailed the Channel and Biscay for years but this is the first time you've been genuinely out of range of easy assistance. You are nervous but competent — you don't make silly mistakes, you prepare thoroughly, and you're honest about what you don't know. You lean on the rally fleet for reassurance and check in on the SSB net every morning. Anne handles the navigation. You handle the radio and the engine room. You're both determined to complete the crossing and arrive safely.",
				Tools:        []string{"get_weather", "get_time"},
				KnowledgeDocs: []string{
					"colregs/colregs-simplified.md",
					"regions/atlantic/anchorages.md",
				},
				VesselSpec: &agent.VesselSpec{
					Type:   "sailing",
					Length: "16.5m",
					Flag:   "UK",
					MMSI:   "235002468",
					Rig:    "ketch",
					Engine: "Perkins 4.108",
				},
			},
			{
				ID:           "fast-track",
				Name:         "Fast Track",
				CallSign:     "VEFT2",
				AgentType:    "vessel",
				Nationality:  "Canada",
				Position:     agent.Position{Lat: 16.88, Lon: -25.00},
				SystemPrompt: "You are a professional delivery crew of two — you are the skipper — delivering an X-Yacht 50 called Fast Track on a tight schedule from Lanzarote to Barbados. You have no particular interest in conversation. You are correct on the radio, precise in your position reporting, and entirely focused on making miles efficiently. You give the minimum information necessary, formatted exactly as required by the relevant procedure, then end the call. If someone needs a genuine safety answer you give it fully. Everything else is superfluous. You're currently mid-Atlantic, on watch.",
				Tools:        []string{"get_weather", "get_time"},
				KnowledgeDocs: []string{
					"colregs/colregs-simplified.md",
					"regions/atlantic/anchorages.md",
				},
				VesselSpec: &agent.VesselSpec{
					Type:   "sailing",
					Length: "15.2m",
					Flag:   "Canada",
					MMSI:   "316009876",
					Rig:    "sloop",
					Engine: "Volvo D2-55",
				},
			},
		},
		LocalFlavour: "ARC rally runs a daily SSB net — all participants should monitor. Weather routing is critical; the position of the ITCZ determines whether to go via Cape Verde or direct. Portuguese and Spanish VHF conventions apply in the eastern Atlantic. Trade winds blow NE at 15–25 knots in the belt. Watch schedule discipline is essential on passage. EPIRB registration is mandatory before departure.",
	},
}

// GetRegion returns a Region by its ID. The second return value is false if the region is not found.
func GetRegion(id string) (Region, bool) {
	for _, r := range regions {
		if r.ID == id {
			return r, true
		}
	}
	return Region{}, false
}

// AllRegions returns all available cruising regions.
func AllRegions() []Region {
	return regions
}
