import { useEffect, useRef, useState } from 'react';
import {
  Button,
  CopyButton,
  Group,
  Modal,
  Stack,
  Text,
  Tooltip,
} from '@mantine/core';
import { IconCheck, IconClipboard, IconFileText, IconUser, IconFileExport } from '@tabler/icons-react';
import { useSolarStore } from '@/stores/solar';
import { HEADING_FONT } from '@above-deck/shared/theme/fonts';
import { encodeConfig } from '@/lib/solar/url-state';

export interface ShareModalProps {
  opened: boolean;
  onClose: () => void;
}

function buildShareUrl(): string {
  const state = useSolarStore.getState();
  const config: Record<string, unknown> = {
    boatName: state.boatName,
    boatType: state.boatType,
    boatLengthFt: state.boatLengthFt,
    cruisingStyle: state.cruisingStyle,
    crewSize: state.crewSize,
    regionName: state.regionName,
    systemVoltage: state.systemVoltage,
    acCircuitVoltage: state.acCircuitVoltage,
    batteryChemistry: state.batteryChemistry,
    deratingFactor: state.deratingFactor,
    viewMode: state.viewMode,
    equipment: state.equipment,
  };
  const encoded = encodeConfig(config);
  const base = typeof window !== 'undefined' ? window.location.origin + window.location.pathname : '';
  return `${base}?c=${encoded}`;
}

function buildTextSummary(): string {
  const state = useSolarStore.getState();
  const lines: string[] = [
    'Energy Planner Configuration',
    '============================',
    '',
    `Boat: ${state.boatName || 'Unnamed'} (${state.boatType}, ${state.boatLengthFt}ft)`,
    `Region: ${state.regionName}`,
    `Cruising Style: ${state.cruisingStyle}`,
    `Crew: ${state.crewSize}`,
    `System: ${state.systemVoltage}V DC / ${state.acCircuitVoltage}V AC`,
    `Battery Chemistry: ${state.batteryChemistry === 'lifepo4' ? 'LiFePO4' : 'AGM'}`,
    '',
    'Equipment',
    '---------',
  ];

  const drains = state.equipment.filter((e) => e.type === 'drain' && e.enabled);
  const charges = state.equipment.filter((e) => e.type === 'charge' && e.enabled);
  const stores = state.equipment.filter((e) => e.type === 'store' && e.enabled);

  if (drains.length > 0) {
    lines.push('', 'Drains:');
    for (const d of drains) {
      lines.push(`  - ${d.name}`);
    }
  }
  if (charges.length > 0) {
    lines.push('', 'Charging Sources:');
    for (const c of charges) {
      lines.push(`  - ${c.name}`);
    }
  }
  if (stores.length > 0) {
    lines.push('', 'Storage:');
    for (const s of stores) {
      lines.push(`  - ${s.name}`);
    }
  }

  lines.push('', `Generated by Above Deck Energy Planner`);
  return lines.join('\n');
}

export function ShareModal({ opened, onClose }: ShareModalProps) {
  const [copied, setCopied] = useState(false);
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => () => { if (timerRef.current) clearTimeout(timerRef.current); }, []);

  const handleCopyLink = async () => {
    const url = buildShareUrl();
    try {
      await navigator.clipboard.writeText(url);
      if (timerRef.current) clearTimeout(timerRef.current);
      setCopied(true);
      timerRef.current = setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback: the CopyButton approach handles this
    }
  };

  const handleExportText = async () => {
    const text = buildTextSummary();
    try {
      await navigator.clipboard.writeText(text);
    } catch {
      // Silent fail in test environments
    }
  };

  return (
    <Modal
      opened={opened}
      onClose={onClose}
      title={
        <Text fw={700} ff={HEADING_FONT}>
          Share Configuration
        </Text>
      }
      size="sm"
    >
      <div data-testid="share-modal">
        <Stack gap="md">
          <Button
            leftSection={copied ? <IconCheck size={16} /> : <IconClipboard size={16} />}
            variant="light"
            fullWidth
            onClick={handleCopyLink}
          >
            {copied ? 'Link Copied' : 'Copy Link'}
          </Button>

          <Button
            leftSection={<IconFileText size={16} />}
            variant="light"
            fullWidth
            onClick={handleExportText}
          >
            Export as Text
          </Button>

          <Button
            leftSection={<IconUser size={16} />}
            variant="light"
            fullWidth
            disabled
          >
            Save to Account (coming soon)
          </Button>

          <Button
            leftSection={<IconFileExport size={16} />}
            variant="light"
            fullWidth
            disabled
          >
            Export as PDF (coming soon)
          </Button>
        </Stack>
      </div>
    </Modal>
  );
}
